export interface CTPData {
  coreCC: number;
  hypoperfusedCC: number;
  mismatchCC: number;
  mismatchRatio: number | null; // null when core is 0 (ratio undefined)
  interpretation: string;
  image: string;
}

export interface CaseData {
  id: string;
  age: number;
  sex: string;
  nihssAdmit: number;
  nihssDischarge: number;
  ticiPre: number;
  ticiPost: string; // "3" or "2b" etc
  ticiPostNumeric: number; // for calculations: 3, 2.5 for 2b, 1 for 1, etc
  diagnosis: string;
  diagnosisSub: string;
  summary: string;
  dsaPre: string;
  dsaPost: string;
  dsaPreCaption: string;
  dsaPostCaption: string;
  ctp?: CTPData;
  presentation: string;
  perfusionNote?: string;
  procedureNote: string;
  outcomeNote: string;
}

export const CASES: CaseData[] = [
  {
    id: 'case1',
    age: 39,
    sex: 'Male',
    nihssAdmit: 24,
    nihssDischarge: 6,
    ticiPre: 0,
    ticiPost: '3',
    ticiPostNumeric: 3,
    diagnosis: 'LVO — Anterior',
    diagnosisSub: 'Acute Ischemic Stroke',
    summary: '39-year-old male presenting with severe anterior circulation LVO stroke. Perfusion-guided mechanical thrombectomy achieved full recanalization with dramatic neurological recovery.',
    dsaPre: '/cases/dsa-pre.png',
    dsaPost: '/cases/dsa-post.png',
    dsaPreCaption: 'Lateral DSA: vessel opacification to level of occlusion without distal filling; no antegrade perfusion',
    dsaPostCaption: 'Lateral DSA post-thrombectomy: robust antegrade flow restored with full opacification of all distal branches',
    ctp: {
      coreCC: 86,
      hypoperfusedCC: 143,
      mismatchCC: 57,
      mismatchRatio: 1.7,
      interpretation: 'A mismatch ratio ≥ 1.8 and volume > 15cc defines ideal penumbral selection (DEFUSE-3). This patient\'s ratio of 1.7 and 57cc mismatch confirms substantial salvageable tissue — consistent with the favorable neurological outcome achieved.',
      image: '/cases/ctp-rapid.png',
    },
    presentation: 'Presented with sudden-onset hemiplegia, gaze deviation, and aphasia — classic features of proximal anterior circulation LVO. Admission NIHSS of 24 reflected dense hemispheric involvement.',
    perfusionNote: 'CTP identified an ischemic core of 86 cc with a larger hypoperfused territory of 143 cc (TMax >6s). The 57 cc mismatch and ratio of 1.7 confirmed viable penumbra — tissue at risk but recoverable with timely recanalization.',
    procedureNote: 'Pre-procedure DSA confirmed complete vessel occlusion — TICI 0. Following mechanical thrombectomy, repeat DSA demonstrated TICI 3 recanalization with full restoration of antegrade flow to all distal branches.',
    outcomeNote: 'Discharge NIHSS of 6 represents a 75% reduction (18-point improvement) from admission. This dramatic recovery in a young patient underscores the life-altering impact of rapid, complete recanalization.',
  },
  {
    id: 'case2',
    age: 60,
    sex: 'Male',
    nihssAdmit: 16,
    nihssDischarge: 0,
    ticiPre: 0,
    ticiPost: '3',
    ticiPostNumeric: 3,
    diagnosis: 'LVO — Anterior',
    diagnosisSub: 'Acute Ischemic Stroke',
    summary: '60-year-old male presenting with anterior circulation LVO stroke. Mechanical thrombectomy achieved complete recanalization with full neurological recovery — discharge NIHSS of 0.',
    dsaPre: '/cases/case2-dsa-pre.png',
    dsaPost: '/cases/case2-dsa-post.png',
    dsaPreCaption: 'AP DSA: large vessel occlusion with absent distal filling; no antegrade perfusion',
    dsaPostCaption: 'AP DSA post-thrombectomy: complete restoration of flow with full opacification of all distal branches',
    presentation: 'Presented with acute-onset neurological deficit consistent with anterior circulation large vessel occlusion. Admission NIHSS of 16 indicated moderate-to-severe hemispheric involvement.',
    procedureNote: 'Pre-procedure DSA confirmed complete vessel occlusion — TICI 0. Mechanical thrombectomy achieved TICI 3 recanalization with full restoration of antegrade flow to all distal territories.',
    outcomeNote: 'Discharge NIHSS of 0 represents a complete neurological recovery — 100% improvement from admission.',
  },
  {
    id: 'case3',
    age: 82,
    sex: 'Male',
    nihssAdmit: 16,
    nihssDischarge: 4,
    ticiPre: 0,
    ticiPost: '3',
    ticiPostNumeric: 3,
    diagnosis: 'LVO — Anterior',
    diagnosisSub: 'Acute Ischemic Stroke',
    summary: '82-year-old male presenting with anterior circulation LVO stroke. Despite advanced age, mechanical thrombectomy achieved complete recanalization with significant neurological improvement.',
    dsaPre: '/cases/case3-dsa-pre.png',
    dsaPost: '/cases/case3-dsa-post.png',
    dsaPreCaption: 'AP DSA: large vessel occlusion with markedly reduced distal perfusion',
    dsaPostCaption: 'AP DSA post-thrombectomy: complete recanalization with restored distal flow',
    presentation: 'Presented with acute-onset neurological deficit consistent with anterior circulation large vessel occlusion. Admission NIHSS of 16 indicated moderate-to-severe hemispheric involvement in an elderly patient.',
    procedureNote: 'Pre-procedure DSA confirmed complete vessel occlusion — TICI 0. Mechanical thrombectomy achieved TICI 3 recanalization with complete restoration of antegrade flow.',
    outcomeNote: 'Discharge NIHSS of 4 represents a 75% reduction (12-point improvement) from admission. A significant recovery in an 82-year-old, reinforcing that age alone should not exclude patients from thrombectomy.',
  },
  {
    id: 'case4',
    age: 76,
    sex: 'Male',
    nihssAdmit: 8,
    nihssDischarge: 5,
    ticiPre: 0,
    ticiPost: '3',
    ticiPostNumeric: 3,
    diagnosis: 'LVO — Posterior',
    diagnosisSub: 'Acute Ischemic Stroke',
    summary: '76-year-old male presenting with posterior circulation LVO and small ischemic core on CT perfusion. Mechanical thrombectomy achieved complete recanalization with neurological improvement.',
    dsaPre: '/cases/case4-dsa-pre.png',
    dsaPost: '/cases/case4-dsa-post.png',
    dsaPreCaption: 'Lateral DSA: posterior circulation vessel occlusion with reduced distal opacification',
    dsaPostCaption: 'Lateral DSA post-thrombectomy: restored antegrade flow with distal branch filling',
    ctp: {
      coreCC: 8,
      hypoperfusedCC: 23,
      mismatchCC: 15,
      mismatchRatio: 2.9,
      interpretation: 'A very small ischemic core (8 cc) with a mismatch ratio of 2.9 indicates predominantly salvageable tissue. This favorable perfusion profile strongly supported intervention despite the lower baseline NIHSS.',
      image: '/cases/case4-ctp.png',
    },
    presentation: 'Presented with acute-onset neurological deficit consistent with posterior circulation large vessel occlusion. Admission NIHSS of 8 indicated a moderate deficit.',
    perfusionNote: 'CTP identified a small ischemic core of 8 cc with a hypoperfused territory of 23 cc (TMax >6s). The 15 cc mismatch and ratio of 2.9 confirmed a highly favorable perfusion profile with predominantly salvageable tissue.',
    procedureNote: 'Pre-procedure DSA confirmed posterior circulation vessel occlusion — TICI 0. Mechanical thrombectomy achieved TICI 3 recanalization with full restoration of antegrade flow to distal branches.',
    outcomeNote: 'Discharge NIHSS of 5 represents a 37.5% reduction (3-point improvement). The small core and favorable perfusion profile justified intervention.',
  },
  {
    id: 'case5',
    age: 59,
    sex: 'Male',
    nihssAdmit: 7,
    nihssDischarge: 4,
    ticiPre: 0,
    ticiPost: '3',
    ticiPostNumeric: 3,
    diagnosis: 'LVO — Anterior',
    diagnosisSub: 'Acute Ischemic Stroke',
    summary: '59-year-old male presenting with anterior circulation LVO stroke and moderate deficit. Mechanical thrombectomy achieved complete recanalization with neurological improvement.',
    dsaPre: '/cases/case5-dsa-pre.png',
    dsaPost: '/cases/case5-dsa-post.png',
    dsaPreCaption: 'AP DSA: large vessel occlusion with reduced distal filling',
    dsaPostCaption: 'AP DSA post-thrombectomy: complete recanalization with restored distal branch opacification',
    presentation: 'Presented with acute-onset neurological deficit consistent with anterior circulation large vessel occlusion. Admission NIHSS of 7 indicated a moderate deficit.',
    procedureNote: 'Pre-procedure DSA confirmed complete vessel occlusion — TICI 0. Mechanical thrombectomy achieved TICI 3 recanalization with full restoration of antegrade flow.',
    outcomeNote: 'Discharge NIHSS of 4 represents a 43% reduction (3-point improvement) from admission with complete recanalization.',
  },
  {
    id: 'case6',
    age: 55,
    sex: 'Male',
    nihssAdmit: 26,
    nihssDischarge: 21,
    ticiPre: 0,
    ticiPost: '3',
    ticiPostNumeric: 3,
    diagnosis: 'LVO — Posterior',
    diagnosisSub: 'Acute Ischemic Stroke',
    summary: '55-year-old male presenting with severe posterior circulation LVO stroke. Despite complete recanalization on angiography, neurological recovery was limited — highlighting that successful reperfusion does not guarantee clinical improvement.',
    dsaPre: '/cases/case6-dsa-pre.png',
    dsaPost: '/cases/case6-dsa-post.png',
    dsaPreCaption: 'Lateral DSA: posterior circulation vessel occlusion with no antegrade perfusion',
    dsaPostCaption: 'Lateral DSA post-thrombectomy: restored antegrade flow with distal branch filling',
    ctp: {
      coreCC: 0,
      hypoperfusedCC: 6,
      mismatchCC: 6,
      mismatchRatio: null,
      interpretation: 'No measurable ischemic core (0 cc) with minimal hypoperfused territory (6 cc). Mismatch ratio is not applicable when core volume is zero. Despite favorable perfusion imaging, the severe clinical deficit (NIHSS 26) with minimal imaging correlate suggests early presentation or perfusion imaging limitations.',
      image: '/cases/case6-ctp.png',
    },
    presentation: 'Presented with severe acute-onset neurological deficit consistent with posterior circulation large vessel occlusion. Admission NIHSS of 26 reflected dense involvement.',
    perfusionNote: 'CTP showed no measurable ischemic core (0 cc) with only 6 cc hypoperfused territory. The discrepancy between severe clinical deficit and minimal perfusion abnormality suggested very early presentation or imaging timing limitations.',
    procedureNote: 'Pre-procedure DSA confirmed posterior circulation vessel occlusion — TICI 0. Mechanical thrombectomy achieved TICI 3 recanalization with full restoration of antegrade flow.',
    outcomeNote: 'Discharge NIHSS of 21 represents only a 19% reduction (5-point improvement) despite complete recanalization. This case illustrates that angiographic success does not always translate to proportional clinical recovery.',
  },
  {
    id: 'case7',
    age: 66,
    sex: 'Male',
    nihssAdmit: 36,
    nihssDischarge: 9,
    ticiPre: 0,
    ticiPost: '1',
    ticiPostNumeric: 1,
    diagnosis: 'LVO — Anterior',
    diagnosisSub: 'Acute Ischemic Stroke',
    summary: '66-year-old male presenting with very severe anterior circulation LVO stroke (NIHSS 36). Thrombectomy achieved only minimal reperfusion (TICI 1), yet the patient demonstrated substantial neurological recovery.',
    dsaPre: '/cases/case7-dsa-pre.png',
    dsaPost: '/cases/case7-dsa-post.png',
    dsaPreCaption: 'AP DSA: complete vessel occlusion with no distal filling',
    dsaPostCaption: 'AP DSA post-thrombectomy: minimal reperfusion with limited distal flow (TICI 1)',
    presentation: 'Presented with very severe acute-onset neurological deficit consistent with anterior circulation large vessel occlusion. Admission NIHSS of 36 — one of the highest in this series — reflected near-complete hemispheric involvement.',
    procedureNote: 'Pre-procedure DSA confirmed complete vessel occlusion — TICI 0. Despite thrombectomy attempts, only minimal reperfusion was achieved — TICI 1 with limited penetration past the occlusion and minimal distal flow.',
    outcomeNote: 'Discharge NIHSS of 9 represents a 75% reduction (27-point improvement) despite suboptimal recanalization. This surprising recovery suggests possible collateral-mediated perfusion or delayed recanalization.',
  },
  {
    id: 'case8',
    age: 82,
    sex: 'Female',
    nihssAdmit: 29,
    nihssDischarge: 17,
    ticiPre: 0,
    ticiPost: '2b',
    ticiPostNumeric: 2.5,
    diagnosis: 'LVO — Anterior',
    diagnosisSub: 'Acute Ischemic Stroke',
    summary: '82-year-old female presenting with severe anterior circulation LVO stroke. Mechanical thrombectomy achieved substantial reperfusion (TICI 2b) with moderate neurological improvement.',
    dsaPre: '/cases/case8-dsa-pre.png',
    dsaPost: '/cases/case8-dsa-post.png',
    dsaPreCaption: 'AP DSA: large vessel occlusion with absent distal filling beyond the occlusion',
    dsaPostCaption: 'AP DSA post-thrombectomy: substantial reperfusion with improved distal branch filling (TICI 2b)',
    presentation: 'Presented with severe acute-onset neurological deficit consistent with anterior circulation large vessel occlusion. Admission NIHSS of 29 reflected dense hemispheric involvement in an elderly female patient.',
    procedureNote: 'Pre-procedure DSA confirmed complete vessel occlusion — TICI 0. Mechanical thrombectomy achieved TICI 2b — substantial reperfusion of more than half of the previously occluded territory.',
    outcomeNote: 'Discharge NIHSS of 17 represents a 41% reduction (12-point improvement) from admission. Meaningful recovery in an 82-year-old despite incomplete recanalization.',
  },
  {
    id: 'case9',
    age: 73,
    sex: 'Female',
    nihssAdmit: 2,
    nihssDischarge: 0,
    ticiPre: 0,
    ticiPost: '3',
    ticiPostNumeric: 3,
    diagnosis: 'LVO — Posterior',
    diagnosisSub: 'Acute Ischemic Stroke',
    summary: '73-year-old female presenting with mild deficit despite posterior circulation LVO on imaging. CT perfusion confirmed no ischemic core with salvageable penumbra. Mechanical thrombectomy achieved complete recanalization and full neurological recovery.',
    dsaPre: '/cases/case9-dsa-pre.png',
    dsaPost: '/cases/case9-dsa-post.png',
    dsaPreCaption: 'AP DSA: posterior circulation vessel occlusion with collateral-dependent distal filling',
    dsaPostCaption: 'AP DSA post-thrombectomy: complete recanalization with robust distal branch filling',
    ctp: {
      coreCC: 0,
      hypoperfusedCC: 23,
      mismatchCC: 23,
      mismatchRatio: null,
      interpretation: 'No measurable ischemic core (0 cc) with 23 cc of hypoperfused tissue — entirely salvageable penumbra. The zero core volume with a mild clinical deficit (NIHSS 2) likely reflects excellent collateral circulation maintaining tissue viability. This profile strongly supported intervention to prevent progression.',
      image: '/cases/case9-ctp.png',
    },
    presentation: 'Presented with mild neurological deficit despite confirmed posterior circulation LVO on imaging. Admission NIHSS of 2 — the lowest in this series — reflected excellent collateral perfusion maintaining tissue viability.',
    perfusionNote: 'CTP showed no measurable ischemic core (0 cc) with 23 cc of hypoperfused territory (TMax >6s). All at-risk tissue was potentially salvageable. The mild clinical deficit correlated with preserved collateral flow.',
    procedureNote: 'Pre-procedure DSA confirmed posterior circulation vessel occlusion — TICI 0. Mechanical thrombectomy achieved TICI 3 recanalization with complete restoration of antegrade flow to all distal branches.',
    outcomeNote: 'Discharge NIHSS of 0 represents complete neurological recovery. Intervention prevented potential progression to completed infarct in a patient with favorable collateral-dependent perfusion.',
  },
];
